"""Tests for cuTile pipeline on SDFGs generated by the DaCe Python frontend."""

import dace
import numpy as np

from dace.sdfg import nodes
from dace.libraries.cutile.nodes import TileAddLibraryNode
from dace.libraries.cutile.transformations.pipeline import apply_cutile_pipeline


FN = dace.symbol("FN", dtype=dace.int32)
FM = dace.symbol("FM", dtype=dace.int32)


@dace.program
def frontend_vadd_program(
    A: dace.float32[24, 20],
    B: dace.float32[24, 20],
    C: dace.float32[24, 20],
):
    for i, j in dace.map[0:24, 0:20]:
        C[i, j] = A[i, j] + B[i, j]


@dace.program
def frontend_symbolic_vadd_program(
    A: dace.float32[FN, FM],
    B: dace.float32[FN, FM],
    C: dace.float32[FN, FM],
):
    for i, j in dace.map[0:FN, 0:FM]:
        C[i, j] = A[i, j] + B[i, j]


@dace.program
def frontend_noncanonical_vadd_program(
    A: dace.float64[13, 11],
    B: dace.float64[13, 11],
    C: dace.float64[13, 11],
):
    for i, j in dace.map[1:13:2, 2:10]:
        C[i, j] = A[i, j] + B[i, j]


def _frontend_library_nodes(sdfg: dace.SDFG):
    return [
        node
        for state in sdfg.states()
        for node in state.nodes()
        if isinstance(node, nodes.LibraryNode)
    ]


def test_frontend_vadd_pipeline_structure_and_runtime():
    """Untiled frontend add should tile, transform to TileAdd, and run correctly."""
    sdfg = frontend_vadd_program.to_sdfg(simplify=True)
    count = apply_cutile_pipeline(
        sdfg,
        validate=True,
        apply_map_tiling=True,
        tile_shape=(6, 5),
    )
    assert count >= 1

    lib_nodes = _frontend_library_nodes(sdfg)
    assert any(isinstance(node, TileAddLibraryNode) for node in lib_nodes)

    tasklet_codes = {
        str(node.code)
        for state in sdfg.states()
        for node in state.nodes()
        if isinstance(node, nodes.Tasklet)
    }
    assert "c = a + b" not in tasklet_codes

    sdfg.expand_library_nodes()
    sdfg.validate()

    rng = np.random.default_rng(7001)
    a = rng.uniform(-3.0, 3.0, size=(24, 20)).astype(np.float32)
    b = rng.uniform(-3.0, 3.0, size=(24, 20)).astype(np.float32)
    c = np.zeros((24, 20), dtype=np.float32)

    sdfg(A=a, B=b, C=c)
    np.testing.assert_allclose(c, a + b, rtol=1e-6, atol=1e-6)


def test_frontend_symbolic_vadd_pipeline_structure_and_runtime():
    """Frontend symbolic add should transform and execute with concrete runtime symbols."""
    sdfg = frontend_symbolic_vadd_program.to_sdfg(simplify=True)
    count = apply_cutile_pipeline(
        sdfg,
        validate=True,
        apply_map_tiling=True,
        tile_shape=(4, 3),
    )
    assert count >= 1

    lib_nodes = _frontend_library_nodes(sdfg)
    assert any(isinstance(node, TileAddLibraryNode) for node in lib_nodes)

    sdfg.expand_library_nodes()
    sdfg.validate()

    n_val = np.int32(18)
    m_val = np.int32(14)
    rng = np.random.default_rng(7002)
    a = rng.uniform(-9.0, 9.0, size=(n_val, m_val)).astype(np.float32)
    b = rng.uniform(-9.0, 9.0, size=(n_val, m_val)).astype(np.float32)
    c = np.zeros((n_val, m_val), dtype=np.float32)

    sdfg(A=a, B=b, C=c, FN=n_val, FM=m_val)
    np.testing.assert_allclose(c, a + b, rtol=1e-6, atol=1e-6)


def test_frontend_noncanonical_strided_add_pipeline_structure_and_runtime():
    """Frontend non-canonical strided map should keep structure and run correctly."""
    sdfg = frontend_noncanonical_vadd_program.to_sdfg(simplify=True)
    count = apply_cutile_pipeline(
        sdfg,
        validate=True,
        apply_map_tiling=False,
    )
    assert count >= 1

    state = sdfg.states()[0]
    map_entries = [n for n in state.nodes() if isinstance(n, nodes.MapEntry)]
    tasklets = [n for n in state.nodes() if isinstance(n, nodes.Tasklet)]
    assert len(map_entries) == 1
    assert len(tasklets) == 1

    # Ensure the strided/non-zero-start frontend range is still represented.
    map_range = str(map_entries[0].map.range)
    assert "1:13:2" in map_range
    assert "2:10" in map_range

    assert len(tasklets[0].in_connectors) == 2
    assert len(tasklets[0].out_connectors) == 1

    sdfg.expand_library_nodes()
    sdfg.validate()

    rng = np.random.default_rng(7003)
    a = rng.uniform(-5.0, 5.0, size=(13, 11)).astype(np.float64)
    b = rng.uniform(-5.0, 5.0, size=(13, 11)).astype(np.float64)
    c = rng.uniform(-2.0, 2.0, size=(13, 11)).astype(np.float64)

    expected = c.copy()
    expected[1:13:2, 2:10] = a[1:13:2, 2:10] + b[1:13:2, 2:10]

    sdfg(A=a, B=b, C=c)
    np.testing.assert_allclose(c, expected, rtol=0.0, atol=1e-12)


if __name__ == "__main__":
    # run all functions with names starting with "test_"
    for name, fn in sorted(globals().items()):
        if name.startswith("test_") and callable(fn):
            print(f"Running {name}...")
            fn()

    print("\nAll tests passed!")
