"""Tests for cuTile pipeline on SDFGs generated by the DaCe Python frontend."""

import dace
import math
import numpy as np
import pytest

from dace.sdfg import nodes
from dace.libraries.cutile.nodes import TileOpLibraryNode, TileSymbolicMaskedOpLibraryNode
from dace.libraries.cutile.transformations.pipeline import apply_cutile_pipeline


FN = dace.symbol("FN", dtype=dace.int32)
FM = dace.symbol("FM", dtype=dace.int32)


@dace.program
def frontend_vadd_program(
    A: dace.float32[24, 20],
    B: dace.float32[24, 20],
    C: dace.float32[24, 20],
):
    for i, j in dace.map[0:24, 0:20]:
        C[i, j] = A[i, j] + B[i, j]


@dace.program
def frontend_symbolic_vadd_program(
    A: dace.float32[FN, FM],
    B: dace.float32[FN, FM],
    C: dace.float32[FN, FM],
):
    for i, j in dace.map[0:FN, 0:FM]:
        C[i, j] = A[i, j] + B[i, j]


@dace.program
def frontend_vselfadd_program(
    A: dace.float32[24, 20],
    C: dace.float32[24, 20],
):
    for i, j in dace.map[0:24, 0:20]:
        C[i, j] = A[i, j] + A[i, j]




@dace.program
def frontend_noncanonical_vadd_program(
    A: dace.float64[13, 11],
    B: dace.float64[13, 11],
    C: dace.float64[13, 11],
):
    for i, j in dace.map[1:13:2, 2:10]:
        C[i, j] = A[i, j] + B[i, j]


@dace.program
def frontend_large_prime_stride_vadd_program(
    A: dace.float64[211, 197],
    B: dace.float64[211, 197],
    C: dace.float64[211, 197],
):
    for i, j in dace.map[2:209:3, 5:194:7]:
        C[i, j] = A[i, j] + B[i, j]


@dace.program
def frontend_large_prime_stride_nondivisible_vadd_program(
    A: dace.float64[223, 199],
    B: dace.float64[223, 199],
    C: dace.float64[223, 199],
):
    # Both dimensions intentionally use ranges where (end - start) is not
    # divisible by the stride.
    for i, j in dace.map[3:221:7, 2:198:5]:
        C[i, j] = A[i, j] + B[i, j]


def _frontend_library_nodes(sdfg: dace.SDFG):
    return [
        node
        for state in sdfg.states()
        for node in state.nodes()
        if isinstance(node, nodes.LibraryNode)
    ]


def test_frontend_vadd_pipeline_structure_and_runtime():
    """Untiled frontend add should tile, transform to TileAdd, and run correctly."""
    sdfg = frontend_vadd_program.to_sdfg(simplify=True)
    count = apply_cutile_pipeline(
        sdfg,
        validate=True,
        apply_map_tiling=True,
        tile_shape=(6, 5),
    )
    assert count >= 1

    lib_nodes = _frontend_library_nodes(sdfg)
    assert any(isinstance(node, TileOpLibraryNode) for node in lib_nodes)

    tasklet_codes = {
        str(node.code)
        for state in sdfg.states()
        for node in state.nodes()
        if isinstance(node, nodes.Tasklet)
    }
    assert "c = a + b" not in tasklet_codes

    sdfg.expand_library_nodes()
    sdfg.validate()

    rng = np.random.default_rng(7001)
    a = rng.uniform(-3.0, 3.0, size=(24, 20)).astype(np.float32)
    b = rng.uniform(-3.0, 3.0, size=(24, 20)).astype(np.float32)
    c = np.zeros((24, 20), dtype=np.float32)

    sdfg(A=a, B=b, C=c)
    np.testing.assert_allclose(c, a + b, rtol=1e-6, atol=1e-6)


def test_frontend_symbolic_vadd_pipeline_structure_and_runtime():
    """Frontend symbolic add should transform and execute with concrete runtime symbols."""
    sdfg = frontend_symbolic_vadd_program.to_sdfg(simplify=True)
    count = apply_cutile_pipeline(
        sdfg,
        validate=True,
        apply_map_tiling=True,
        tile_shape=(4, 3),
    )
    assert count >= 1, f"Expected at least 1 transformation, but got {count}"

    lib_nodes = _frontend_library_nodes(sdfg)
    assert any(isinstance(node, TileOpLibraryNode) for node in lib_nodes), "Expected at least one TileOpLibraryNode in the transformed SDFG."

    sdfg.expand_library_nodes()
    sdfg.validate()

    n_val = np.int32(18)
    m_val = np.int32(14)
    rng = np.random.default_rng(7002)
    a = rng.uniform(-9.0, 9.0, size=(n_val, m_val)).astype(np.float32)
    b = rng.uniform(-9.0, 9.0, size=(n_val, m_val)).astype(np.float32)
    c = np.zeros((n_val, m_val), dtype=np.float32)

    sdfg(A=a, B=b, C=c, FN=n_val, FM=m_val)
    np.testing.assert_allclose(c, a + b, rtol=1e-6, atol=1e-6)


def test_frontend_vselfadd_pipeline_structure_and_runtime():
    """Frontend self-add should transform and execute numerically correctly."""
    sdfg = frontend_vselfadd_program.to_sdfg(simplify=True)
    count = apply_cutile_pipeline(
        sdfg,
        validate=True,
        apply_map_tiling=True,
        tile_shape=(6, 5),
    )
    assert count >= 1

    lib_nodes = _frontend_library_nodes(sdfg)
    assert any(isinstance(node, TileOpLibraryNode) for node in lib_nodes)

    sdfg.expand_library_nodes()
    sdfg.validate()

    rng = np.random.default_rng(7006)
    a = rng.uniform(-3.0, 3.0, size=(24, 20)).astype(np.float32)
    c = np.zeros((24, 20), dtype=np.float32)

    sdfg(A=a, C=c)
    np.testing.assert_allclose(c, a + a, rtol=1e-6, atol=1e-6)


def test_frontend_noncanonical_strided_add_pipeline_structure_and_runtime():
    """Frontend non-canonical strided map should not not get replaced by library
    nodes because we do not apply map tiling and run correctly."""
    sdfg = frontend_noncanonical_vadd_program.to_sdfg(simplify=True)
    count = apply_cutile_pipeline(
        sdfg,
        validate=True,
        apply_map_tiling=False,
    )
    assert count == 0

    state = sdfg.states()[0]
    map_entries = [n for n in state.nodes() if isinstance(n, nodes.MapEntry)]
    tasklets = [n for n in state.nodes() if isinstance(n, nodes.Tasklet)]
    assert len(map_entries) == 1
    assert len(tasklets) == 1

    # Ensure the strided/non-zero-start frontend range is still represented.
    map_range = str(map_entries[0].map.range)
    assert "1:13:2" in map_range
    assert "2:10" in map_range

    assert len(tasklets[0].in_connectors) == 2
    assert len(tasklets[0].out_connectors) == 1

    sdfg.expand_library_nodes()
    sdfg.validate()

    rng = np.random.default_rng(7003)
    a = rng.uniform(-5.0, 5.0, size=(13, 11)).astype(np.float64)
    b = rng.uniform(-5.0, 5.0, size=(13, 11)).astype(np.float64)
    c = rng.uniform(-2.0, 2.0, size=(13, 11)).astype(np.float64)

    expected = c.copy()
    expected[1:13:2, 2:10] = a[1:13:2, 2:10] + b[1:13:2, 2:10]

    sdfg(A=a, B=b, C=c)
    np.testing.assert_allclose(c, expected, rtol=0.0, atol=1e-12)


@pytest.mark.parametrize("tile_shape", [(10, 11), (16, 9)])
def test_frontend_large_prime_strided_add_with_nonmultiple_tile_shape(tile_shape):
    """Large prime-strided frontend map should remain correct after map tiling."""
    sdfg = frontend_large_prime_stride_vadd_program.to_sdfg(simplify=True)
    count = apply_cutile_pipeline(
        sdfg,
        validate=True,
        apply_map_tiling=True,
        tile_shape=tile_shape,
    )
    assert count >= 2

    lib_nodes = _frontend_library_nodes(sdfg)
    sym_nodes = [n for n in lib_nodes if isinstance(n, TileSymbolicMaskedOpLibraryNode)]
    assert sym_nodes
    assert all(n.mask_condition is not None for n in sym_nodes)

    sdfg.expand_library_nodes()
    sdfg.validate()

    rng = np.random.default_rng(7004)
    a = rng.uniform(-8.0, 8.0, size=(211, 197)).astype(np.float64)
    b = rng.uniform(-8.0, 8.0, size=(211, 197)).astype(np.float64)
    c = rng.uniform(-3.0, 3.0, size=(211, 197)).astype(np.float64)

    expected = c.copy()
    expected[2:209:3, 5:194:7] = a[2:209:3, 5:194:7] + b[2:209:3, 5:194:7]

    sdfg(A=a, B=b, C=c)
    np.testing.assert_allclose(c, expected, rtol=0.0, atol=1e-12)


@pytest.mark.parametrize("tile_shape", [(13, 10), (17, 12)])
def test_frontend_large_prime_strided_add_with_nondivisible_ranges(tile_shape):
    """Prime strides with non-divisible ranges should remain correct after tiling."""
    sdfg = frontend_large_prime_stride_nondivisible_vadd_program.to_sdfg(simplify=True)
    count = apply_cutile_pipeline(
        sdfg,
        validate=True,
        apply_map_tiling=True,
        tile_shape=tile_shape,
    )
    assert count >= 2

    lib_nodes = _frontend_library_nodes(sdfg)
    sym_nodes = [n for n in lib_nodes if isinstance(n, TileSymbolicMaskedOpLibraryNode)]
    assert sym_nodes
    assert all(n.mask_condition is not None for n in sym_nodes)

    sdfg.expand_library_nodes()
    sdfg.validate()

    rng = np.random.default_rng(7005)
    a = rng.uniform(-10.0, 10.0, size=(223, 199)).astype(np.float64)
    b = rng.uniform(-10.0, 10.0, size=(223, 199)).astype(np.float64)
    c = rng.uniform(-4.0, 4.0, size=(223, 199)).astype(np.float64)

    expected = c.copy()
    expected[3:221:7, 2:198:5] = a[3:221:7, 2:198:5] + b[3:221:7, 2:198:5]

    sdfg(A=a, B=b, C=c)
    np.testing.assert_allclose(c, expected, rtol=0.0, atol=1e-12)


# ---------------------------------------------------------------------------
# Unary operations
# ---------------------------------------------------------------------------

@dace.program
def frontend_negate_program(
    A: dace.float64[24, 20],
    C: dace.float64[24, 20],
):
    for i, j in dace.map[0:24, 0:20]:
        C[i, j] = -A[i, j]


@dace.program
def frontend_abs_program(
    A: dace.float64[24, 20],
    C: dace.float64[24, 20],
):
    for i, j in dace.map[0:24, 0:20]:
        C[i, j] = abs(A[i, j])


@dace.program
def frontend_cos_program(
    A: dace.float64[24, 20],
    C: dace.float64[24, 20],
):
    for i, j in dace.map[0:24, 0:20]:
        with dace.tasklet:
            a << A[i, j]
            c >> C[i, j]
            c = math.cos(a)


# ---------------------------------------------------------------------------
# Binary operations with constants
# ---------------------------------------------------------------------------

@dace.program
def frontend_a_minus_const_program(
    A: dace.float64[24, 20],
    C: dace.float64[24, 20],
):
    for i, j in dace.map[0:24, 0:20]:
        C[i, j] = A[i, j] - 5


@dace.program
def frontend_const_minus_a_program(
    A: dace.float64[24, 20],
    C: dace.float64[24, 20],
):
    for i, j in dace.map[0:24, 0:20]:
        C[i, j] = 3 - A[i, j]


@dace.program
def frontend_a_times_const_program(
    A: dace.float64[24, 20],
    C: dace.float64[24, 20],
):
    for i, j in dace.map[0:24, 0:20]:
        C[i, j] = A[i, j] * 3


# ---------------------------------------------------------------------------
# Constant-constant (frontend constant-folds 2*3 → 6)
# ---------------------------------------------------------------------------

@dace.program
def frontend_const_const_program(
    C: dace.float64[24, 20],
):
    for i, j in dace.map[0:24, 0:20]:
        C[i, j] = 2 * 3


# ---------------------------------------------------------------------------
# Test implementations
# ---------------------------------------------------------------------------

def test_frontend_negate_pipeline_structure_and_runtime():
    """Frontend negation should transform to TileUnaryOp and run correctly."""
    sdfg = frontend_negate_program.to_sdfg(simplify=True)
    count = apply_cutile_pipeline(
        sdfg,
        validate=True,
        apply_map_tiling=True,
        tile_shape=(6, 5),
    )
    assert count >= 1

    lib_nodes = _frontend_library_nodes(sdfg)
    assert any(isinstance(node, TileOpLibraryNode) for node in lib_nodes)

    sdfg.expand_library_nodes()
    sdfg.validate()

    rng = np.random.default_rng(8001)
    a = rng.uniform(-3.0, 3.0, size=(24, 20))
    c = np.zeros((24, 20), dtype=np.float64)

    sdfg(A=a, C=c)
    np.testing.assert_allclose(c, -a, rtol=0.0, atol=1e-12)


def test_frontend_abs_pipeline_structure_and_runtime():
    """Frontend abs should transform to TileUnaryOp and run correctly."""
    sdfg = frontend_abs_program.to_sdfg(simplify=True)
    count = apply_cutile_pipeline(
        sdfg,
        validate=True,
        apply_map_tiling=True,
        tile_shape=(6, 5),
    )
    assert count >= 1

    lib_nodes = _frontend_library_nodes(sdfg)
    assert any(isinstance(node, TileOpLibraryNode) for node in lib_nodes)

    sdfg.expand_library_nodes()
    sdfg.validate()

    rng = np.random.default_rng(8002)
    a = rng.uniform(-3.0, 3.0, size=(24, 20))
    c = np.zeros((24, 20), dtype=np.float64)

    sdfg(A=a, C=c)
    np.testing.assert_allclose(c, np.abs(a), rtol=0.0, atol=1e-12)


def test_frontend_cos_pipeline_structure_and_runtime():
    """Frontend cos (explicit tasklet) should transform to TileUnaryOp and run correctly."""
    sdfg = frontend_cos_program.to_sdfg(simplify=True)
    count = apply_cutile_pipeline(
        sdfg,
        validate=True,
        apply_map_tiling=True,
        tile_shape=(6, 5),
    )
    assert count >= 1

    lib_nodes = _frontend_library_nodes(sdfg)
    assert any(isinstance(node, TileOpLibraryNode) for node in lib_nodes)

    sdfg.expand_library_nodes()
    sdfg.validate()

    rng = np.random.default_rng(8003)
    a = rng.uniform(-3.0, 3.0, size=(24, 20))
    c = np.zeros((24, 20), dtype=np.float64)

    sdfg(A=a, C=c)
    np.testing.assert_allclose(c, np.cos(a), rtol=1e-12, atol=1e-12)


def test_frontend_a_minus_const_pipeline_structure_and_runtime():
    """Frontend A - 5 should transform to TileBinaryOp with constant and run correctly."""
    sdfg = frontend_a_minus_const_program.to_sdfg(simplify=True)
    count = apply_cutile_pipeline(
        sdfg,
        validate=True,
        apply_map_tiling=True,
        tile_shape=(6, 5),
    )
    assert count >= 1

    lib_nodes = _frontend_library_nodes(sdfg)
    assert any(isinstance(node, TileOpLibraryNode) for node in lib_nodes)

    sdfg.expand_library_nodes()
    sdfg.validate()

    rng = np.random.default_rng(8004)
    a = rng.uniform(-3.0, 3.0, size=(24, 20))
    c = np.zeros((24, 20), dtype=np.float64)

    sdfg(A=a, C=c)
    np.testing.assert_allclose(c, a - 5, rtol=0.0, atol=1e-12)


def test_frontend_const_minus_a_pipeline_structure_and_runtime():
    """Frontend 3 - A should transform to TileBinaryOp with constant and run correctly."""
    sdfg = frontend_const_minus_a_program.to_sdfg(simplify=True)
    count = apply_cutile_pipeline(
        sdfg,
        validate=True,
        apply_map_tiling=True,
        tile_shape=(6, 5),
    )
    assert count >= 1

    lib_nodes = _frontend_library_nodes(sdfg)
    assert any(isinstance(node, TileOpLibraryNode) for node in lib_nodes)

    sdfg.expand_library_nodes()
    sdfg.validate()

    rng = np.random.default_rng(8005)
    a = rng.uniform(-3.0, 3.0, size=(24, 20))
    c = np.zeros((24, 20), dtype=np.float64)

    sdfg(A=a, C=c)
    np.testing.assert_allclose(c, 3 - a, rtol=0.0, atol=1e-12)


def test_frontend_a_times_const_pipeline_structure_and_runtime():
    """Frontend A * 3 should transform to TileBinaryOp with constant and run correctly."""
    sdfg = frontend_a_times_const_program.to_sdfg(simplify=True)
    count = apply_cutile_pipeline(
        sdfg,
        validate=True,
        apply_map_tiling=True,
        tile_shape=(6, 5),
    )
    assert count >= 1

    lib_nodes = _frontend_library_nodes(sdfg)
    assert any(isinstance(node, TileOpLibraryNode) for node in lib_nodes)

    sdfg.expand_library_nodes()
    sdfg.validate()

    rng = np.random.default_rng(8006)
    a = rng.uniform(-3.0, 3.0, size=(24, 20))
    c = np.zeros((24, 20), dtype=np.float64)

    sdfg(A=a, C=c)
    np.testing.assert_allclose(c, a * 3, rtol=0.0, atol=1e-12)


def test_frontend_const_const_pipeline_runtime():
    """Frontend 2*3 is constant-folded to 6 by the frontend; pipeline tiles the map."""
    sdfg = frontend_const_const_program.to_sdfg(simplify=True)
    count = apply_cutile_pipeline(
        sdfg,
        validate=True,
        apply_map_tiling=True,
        tile_shape=(6, 5),
    )
    assert count >= 1

    sdfg.expand_library_nodes()
    sdfg.validate()

    c = np.zeros((24, 20), dtype=np.float64)
    sdfg(C=c)
    np.testing.assert_allclose(c, np.full((24, 20), 6.0), rtol=0.0, atol=1e-12)


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-q"]))
