"""Full-pipeline integration tests for symbolic-masked and if-else cuTile operations.

This file fills the gap identified after the previous session: code-structure tests and
direct library-node C++ tests exist, but end-to-end GPU integration tests do not.

Node types generated by the pipeline and tested here:

  TileIfElseOpLibraryNode  (generated from @dace.program if-else branches)
    - Value-comparison conditions: A > 0, A < B, A >= 0, etc.
    - Boolean-like float mask input: `if Mask > 0`
    - All-true / all-false input edge cases
    - Symbolic array sizes

  TileSymbolicMaskedOpLibraryNode  (generated from strided @dace.program maps)
    - Stride-2 map in one dimension → even-element mask
    - Both-dimension stride → row-and-column mask
    - Non-square strided arrays
    - Verify only strided elements get updated (others preserved)

Both node types have Python-backend expansions.  Every GPU test here follows:
  @dace.program → to_sdfg() → sdfg.backend=Python → apply_cutile_pipeline()
  → sdfg.compile() → run on GPU → np.testing.assert_allclose(NumPy reference)

Note on TileRuntimeMaskedOpLibraryNode:
  This node type is NOT generated by apply_cutile_pipeline(); it is only
  created programmatically.  Its Python-backend expansion is exercised via the
  code-structure tests in cutile_masked_python_backend_test.py.  A boolean-mask
  condition expressed as `if Mask[i,j] > 0:` in a @dace.program produces a
  TileIfElseOpLibraryNode with the same runtime-mask semantics.
"""

import numpy as np
import pytest

import dace
from dace import dtypes
from dace.codegen import codegen as dace_codegen
from dace.libraries.cutile.nodes.if_else_op import TileIfElseOpLibraryNode
from dace.libraries.cutile.nodes import TileSymbolicMaskedOpLibraryNode
from dace.libraries.cutile.transformations.pipeline import apply_cutile_pipeline
from dace.sdfg import nodes


cp = pytest.importorskip("cupy")
pytest.importorskip("cuda.tile")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_SZ = dace.symbol("SZ", dtype=dace.int32)


def _frame_code_of(sdfg: dace.SDFG) -> str:
    code_objects = dace_codegen.generate_code(sdfg)
    return next(co.clean_code for co in code_objects if co.name == sdfg.name)


def _lib_nodes(sdfg: dace.SDFG):
    return [
        n
        for state in sdfg.states()
        for n in state.nodes()
        if isinstance(n, nodes.LibraryNode)
    ]


def _count(sdfg, cls):
    return sum(1 for n in _lib_nodes(sdfg) if isinstance(n, cls))


def _pipeline_py(sdfg: dace.SDFG, **kw) -> dace.SDFG:
    """Set Python backend and run the cuTile pipeline."""
    sdfg.backend = dtypes.BackendLanguage.Python
    apply_cutile_pipeline(sdfg, **kw)
    return sdfg


# ---------------------------------------------------------------------------
# @dace.program definitions — if-else, float32 concrete sizes
# ---------------------------------------------------------------------------


@dace.program
def pybe_ifelse_const_branch(A: dace.float32[16, 16], B: dace.float32[16, 16]):
    """A > 0 → B -= 1  else B += 1."""
    for i, j in dace.map[0:16, 0:16]:
        if A[i, j] > 0:
            B[i, j] = B[i, j] - 1.0
        else:
            B[i, j] = B[i, j] + 1.0


@dace.program
def pybe_ifelse_array_branch(
    A: dace.float32[16, 16],
    B: dace.float32[16, 16],
    C: dace.float32[16, 16],
):
    """A > 0 → C += B  else C -= B."""
    for i, j in dace.map[0:16, 0:16]:
        if A[i, j] > 0:
            C[i, j] = C[i, j] + B[i, j]
        else:
            C[i, j] = C[i, j] - B[i, j]


@dace.program
def pybe_ifelse_lt_branch(
    A: dace.float32[16, 16],
    B: dace.float32[16, 16],
    C: dace.float32[16, 16],
):
    """A < B → C = A + B  else C = A - B."""
    for i, j in dace.map[0:16, 0:16]:
        if A[i, j] < B[i, j]:
            C[i, j] = A[i, j] + B[i, j]
        else:
            C[i, j] = A[i, j] - B[i, j]


@dace.program
def pybe_ifelse_ge_sq_abs(A: dace.float32[16, 16], B: dace.float32[16, 16]):
    """A >= 0 → B = A*A  else B = abs(A)."""
    for i, j in dace.map[0:16, 0:16]:
        if A[i, j] >= 0:
            B[i, j] = A[i, j] * A[i, j]
        else:
            B[i, j] = abs(A[i, j])


@dace.program
def pybe_ifelse_le_const(A: dace.float32[16, 16], B: dace.float32[16, 16]):
    """A <= 0 → B = A * 3  else B = A / 2."""
    for i, j in dace.map[0:16, 0:16]:
        if A[i, j] <= 0:
            B[i, j] = A[i, j] * 3.0
        else:
            B[i, j] = A[i, j] / 2.0


@dace.program
def pybe_ifelse_ne_neg(A: dace.float32[16, 16], B: dace.float32[16, 16]):
    """A != 0 → B = -A  else B = A + 1."""
    for i, j in dace.map[0:16, 0:16]:
        if A[i, j] != 0:
            B[i, j] = -A[i, j]
        else:
            B[i, j] = A[i, j] + 1.0


@dace.program
def pybe_ifelse_float_mask(
    A: dace.float32[16, 16],
    B: dace.float32[16, 16],
    Mask: dace.float32[16, 16],
    C: dace.float32[16, 16],
):
    """if Mask > 0: C = A + B  else: C = C.  (Runtime boolean mask via float array.)"""
    for i, j in dace.map[0:16, 0:16]:
        if Mask[i, j] > 0:
            C[i, j] = A[i, j] + B[i, j]
        else:
            C[i, j] = C[i, j]


@dace.program
def pybe_ifelse_symbolic(_A: dace.float32[_SZ, _SZ], _B: dace.float32[_SZ, _SZ]):
    """Symbolic SZ: A > 0 → B -= 1  else B += 1."""
    for i, j in dace.map[0:_SZ, 0:_SZ]:
        if _A[i, j] > 0:
            _B[i, j] = _B[i, j] - 1.0
        else:
            _B[i, j] = _B[i, j] + 1.0


# ---------------------------------------------------------------------------
# @dace.program definitions — strided maps (→ symbolic masked ops)
# ---------------------------------------------------------------------------


@dace.program
def pybe_strided_i2_add(
    A: dace.float32[32, 16],
    B: dace.float32[32, 16],
    C: dace.float32[32, 16],
):
    """Stride-2 in i: only even rows get C[i,j] = A[i,j] + B[i,j]."""
    for i, j in dace.map[0:32:2, 0:16]:
        C[i, j] = A[i, j] + B[i, j]


@dace.program
def pybe_strided_i2_negate(A: dace.float32[32, 16], C: dace.float32[32, 16]):
    """Stride-2 in i: only even rows get C[i,j] = -A[i,j]."""
    for i, j in dace.map[0:32:2, 0:16]:
        C[i, j] = -A[i, j]


@dace.program
def pybe_strided_j2_mul(
    A: dace.float32[16, 32],
    B: dace.float32[16, 32],
    C: dace.float32[16, 32],
):
    """Stride-2 in j: only even columns get C[i,j] = A[i,j] * B[i,j]."""
    for i, j in dace.map[0:16, 0:32:2]:
        C[i, j] = A[i, j] * B[i, j]


@dace.program
def pybe_strided_offset_add(
    A: dace.float32[16, 16],
    B: dace.float32[16, 16],
    C: dace.float32[16, 16],
):
    """Non-zero start, stride-2 in i: rows 2,4,6,...,14 get updated."""
    for i, j in dace.map[2:16:2, 0:16]:
        C[i, j] = A[i, j] + B[i, j]


# ---------------------------------------------------------------------------
# Section A: TileIfElseOp — Python backend structural tests (no GPU)
# ---------------------------------------------------------------------------


class TestIfElsePythonBackendStructure:
    """Verify that if-else @dace.programs produce TileIfElseOpLibraryNode and
    that the Python backend code contains ct.where boilerplate.

    No GPU required — only inspects generated code.
    """

    def test_const_branch_produces_ifelse_node(self):
        """A > 0 if-else program → at least one TileIfElseOpLibraryNode."""
        sdfg = pybe_ifelse_const_branch.to_sdfg(simplify=True)
        _pipeline_py(sdfg)
        assert _count(sdfg, TileIfElseOpLibraryNode) >= 1

    def test_array_branch_produces_ifelse_node(self):
        """A > 0 if-else (two array branches) → TileIfElseOpLibraryNode."""
        sdfg = pybe_ifelse_array_branch.to_sdfg(simplify=True)
        _pipeline_py(sdfg)
        assert _count(sdfg, TileIfElseOpLibraryNode) >= 1

    def test_lt_branch_produces_ifelse_node(self):
        """A < B if-else → TileIfElseOpLibraryNode."""
        sdfg = pybe_ifelse_lt_branch.to_sdfg(simplify=True)
        _pipeline_py(sdfg)
        assert _count(sdfg, TileIfElseOpLibraryNode) >= 1

    def test_float_mask_branch_produces_ifelse_node(self):
        """if Mask > 0 (float boolean mask) → TileIfElseOpLibraryNode."""
        sdfg = pybe_ifelse_float_mask.to_sdfg(simplify=True)
        _pipeline_py(sdfg)
        assert _count(sdfg, TileIfElseOpLibraryNode) >= 1

    def test_const_branch_implementation_is_cutile_python(self):
        """Pipeline with Python backend must set implementation='cutile_python' on IfElse node."""
        sdfg = pybe_ifelse_const_branch.to_sdfg(simplify=True)
        _pipeline_py(sdfg)
        ifelse_nodes = [n for n in _lib_nodes(sdfg) if isinstance(n, TileIfElseOpLibraryNode)]
        assert ifelse_nodes, "Expected at least one TileIfElseOpLibraryNode"
        assert all(n.implementation == "cutile_python" for n in ifelse_nodes), (
            f"Expected all IfElse nodes to have cutile_python implementation, "
            f"got: {[n.implementation for n in ifelse_nodes]}"
        )

    def test_const_branch_codegen_has_kernel_boilerplate(self):
        """Generated code for if-else Python backend must have @ct.kernel and ct.launch."""
        sdfg = pybe_ifelse_const_branch.to_sdfg(simplify=True)
        _pipeline_py(sdfg)
        code = _frame_code_of(sdfg)
        assert "@ct.kernel" in code, "Expected @ct.kernel decorator in generated code"
        assert "ct.launch" in code, "Expected ct.launch call in generated code"

    def test_lt_branch_codegen_has_kernel_boilerplate(self):
        """A < B if-else must produce @ct.kernel / ct.launch kernel code."""
        sdfg = pybe_ifelse_lt_branch.to_sdfg(simplify=True)
        _pipeline_py(sdfg)
        code = _frame_code_of(sdfg)
        assert "@ct.kernel" in code
        assert "ct.launch" in code

    def test_symbolic_size_ifelse_codegen_surfaces_symbols(self):
        """Symbolic SZ must appear in generated kernel code."""
        sdfg = pybe_ifelse_symbolic.to_sdfg(simplify=True)
        _pipeline_py(sdfg)
        code = _frame_code_of(sdfg)
        assert "@ct.kernel" in code
        assert "SZ" in code


# ---------------------------------------------------------------------------
# Section B: TileIfElseOp — Python backend GPU runtime tests
# ---------------------------------------------------------------------------


@pytest.mark.gpu
def test_ifelse_const_branch_python_backend_mixed_input():
    """A > 0: B−=1, else B+=1 with mixed positive/negative A."""
    rng = np.random.default_rng(3001)
    a_np = rng.standard_normal((16, 16)).astype(np.float32)
    b_np = rng.random((16, 16)).astype(np.float32)
    b_orig = b_np.copy()

    sdfg = pybe_ifelse_const_branch.to_sdfg(simplify=True)
    _pipeline_py(sdfg)
    csdfg = sdfg.compile()
    assert csdfg is not None

    csdfg(A=cp.asarray(a_np), B=(b_cp := cp.asarray(b_np)))
    expected = np.where(a_np > 0, b_orig - 1.0, b_orig + 1.0)
    np.testing.assert_allclose(cp.asnumpy(b_cp), expected, rtol=1e-5, atol=1e-6)


@pytest.mark.gpu
def test_ifelse_const_branch_all_positive():
    """All-true case: every element has A > 0 so every element gets B − 1."""
    rng = np.random.default_rng(3002)
    a_np = np.abs(rng.random((16, 16)).astype(np.float32)) + 0.1  # all positive
    b_np = rng.random((16, 16)).astype(np.float32)
    b_orig = b_np.copy()

    sdfg = pybe_ifelse_const_branch.to_sdfg(simplify=True)
    _pipeline_py(sdfg)
    csdfg = sdfg.compile()

    csdfg(A=cp.asarray(a_np), B=(b_cp := cp.asarray(b_np)))
    np.testing.assert_allclose(cp.asnumpy(b_cp), b_orig - 1.0, rtol=1e-5, atol=1e-6)


@pytest.mark.gpu
def test_ifelse_const_branch_all_negative():
    """All-false case: every element has A ≤ 0 so every element gets B + 1."""
    rng = np.random.default_rng(3003)
    a_np = -(np.abs(rng.random((16, 16)).astype(np.float32)) + 0.1)  # all negative
    b_np = rng.random((16, 16)).astype(np.float32)
    b_orig = b_np.copy()

    sdfg = pybe_ifelse_const_branch.to_sdfg(simplify=True)
    _pipeline_py(sdfg)
    csdfg = sdfg.compile()

    csdfg(A=cp.asarray(a_np), B=(b_cp := cp.asarray(b_np)))
    np.testing.assert_allclose(cp.asnumpy(b_cp), b_orig + 1.0, rtol=1e-5, atol=1e-6)


@pytest.mark.gpu
def test_ifelse_array_branch_python_backend():
    """A > 0: C += B, else C -= B."""
    rng = np.random.default_rng(3004)
    a_np = rng.standard_normal((16, 16)).astype(np.float32)
    b_np = rng.random((16, 16)).astype(np.float32)
    c_np = rng.random((16, 16)).astype(np.float32)
    c_orig = c_np.copy()

    sdfg = pybe_ifelse_array_branch.to_sdfg(simplify=True)
    _pipeline_py(sdfg)
    csdfg = sdfg.compile()

    csdfg(A=cp.asarray(a_np), B=cp.asarray(b_np), C=(c_cp := cp.asarray(c_np)))
    expected = np.where(a_np > 0, c_orig + b_np, c_orig - b_np)
    np.testing.assert_allclose(cp.asnumpy(c_cp), expected, rtol=1e-5, atol=1e-6)


@pytest.mark.gpu
def test_ifelse_lt_branch_python_backend():
    """A < B: C = A + B, else C = A − B."""
    rng = np.random.default_rng(3005)
    a_np = rng.standard_normal((16, 16)).astype(np.float32)
    b_np = rng.standard_normal((16, 16)).astype(np.float32)
    c_np = np.zeros((16, 16), dtype=np.float32)

    sdfg = pybe_ifelse_lt_branch.to_sdfg(simplify=True)
    _pipeline_py(sdfg)
    csdfg = sdfg.compile()

    csdfg(A=cp.asarray(a_np), B=cp.asarray(b_np), C=(c_cp := cp.asarray(c_np)))
    expected = np.where(a_np < b_np, a_np + b_np, a_np - b_np)
    np.testing.assert_allclose(cp.asnumpy(c_cp), expected, rtol=1e-5, atol=1e-6)


@pytest.mark.gpu
def test_ifelse_ge_sq_abs_python_backend():
    """A >= 0: B = A², else B = |A|."""
    rng = np.random.default_rng(3006)
    a_np = rng.standard_normal((16, 16)).astype(np.float32)
    b_np = np.zeros((16, 16), dtype=np.float32)

    sdfg = pybe_ifelse_ge_sq_abs.to_sdfg(simplify=True)
    _pipeline_py(sdfg)
    csdfg = sdfg.compile()

    csdfg(A=cp.asarray(a_np), B=(b_cp := cp.asarray(b_np)))
    expected = np.where(a_np >= 0, a_np * a_np, np.abs(a_np))
    np.testing.assert_allclose(cp.asnumpy(b_cp), expected, rtol=1e-5, atol=1e-6)


@pytest.mark.gpu
def test_ifelse_le_const_python_backend():
    """A <= 0: B = A*3, else B = A/2."""
    rng = np.random.default_rng(3007)
    a_np = rng.standard_normal((16, 16)).astype(np.float32)
    b_np = np.zeros((16, 16), dtype=np.float32)

    sdfg = pybe_ifelse_le_const.to_sdfg(simplify=True)
    _pipeline_py(sdfg)
    csdfg = sdfg.compile()

    csdfg(A=cp.asarray(a_np), B=(b_cp := cp.asarray(b_np)))
    expected = np.where(a_np <= 0, a_np * 3.0, a_np / 2.0)
    np.testing.assert_allclose(cp.asnumpy(b_cp), expected, rtol=1e-5, atol=1e-6)


@pytest.mark.gpu
def test_ifelse_ne_neg_python_backend():
    """A != 0: B = -A, else B = A + 1."""
    rng = np.random.default_rng(3008)
    a_np = rng.standard_normal((16, 16)).astype(np.float32)
    b_np = np.zeros((16, 16), dtype=np.float32)

    sdfg = pybe_ifelse_ne_neg.to_sdfg(simplify=True)
    _pipeline_py(sdfg)
    csdfg = sdfg.compile()

    csdfg(A=cp.asarray(a_np), B=(b_cp := cp.asarray(b_np)))
    expected = np.where(a_np != 0, -a_np, a_np + 1.0)
    np.testing.assert_allclose(cp.asnumpy(b_cp), expected, rtol=1e-5, atol=1e-6)


@pytest.mark.gpu
def test_ifelse_float_mask_all_true():
    """Float mask (all 1.0): C = A + B everywhere (equivalent to all-true runtime mask)."""
    rng = np.random.default_rng(3009)
    a_np = rng.random((16, 16)).astype(np.float32)
    b_np = rng.random((16, 16)).astype(np.float32)
    c_np = rng.random((16, 16)).astype(np.float32)
    mask_np = np.ones((16, 16), dtype=np.float32)

    sdfg = pybe_ifelse_float_mask.to_sdfg(simplify=True)
    _pipeline_py(sdfg)
    csdfg = sdfg.compile()

    csdfg(
        A=cp.asarray(a_np), B=cp.asarray(b_np),
        Mask=cp.asarray(mask_np), C=(c_cp := cp.asarray(c_np))
    )
    np.testing.assert_allclose(cp.asnumpy(c_cp), a_np + b_np, rtol=1e-5, atol=1e-6)


@pytest.mark.gpu
def test_ifelse_float_mask_all_false():
    """Float mask (all 0.0): C unchanged everywhere (equivalent to all-false runtime mask)."""
    rng = np.random.default_rng(3010)
    a_np = rng.random((16, 16)).astype(np.float32)
    b_np = rng.random((16, 16)).astype(np.float32)
    c_np = rng.random((16, 16)).astype(np.float32)
    c_orig = c_np.copy()
    mask_np = np.zeros((16, 16), dtype=np.float32)

    sdfg = pybe_ifelse_float_mask.to_sdfg(simplify=True)
    _pipeline_py(sdfg)
    csdfg = sdfg.compile()

    csdfg(
        A=cp.asarray(a_np), B=cp.asarray(b_np),
        Mask=cp.asarray(mask_np), C=(c_cp := cp.asarray(c_np))
    )
    np.testing.assert_allclose(cp.asnumpy(c_cp), c_orig, rtol=1e-5, atol=1e-6)


@pytest.mark.gpu
def test_ifelse_float_mask_mixed():
    """Float mask (mixed 0/1): C = A + B where mask=1, else C preserved."""
    rng = np.random.default_rng(3011)
    a_np = rng.random((16, 16)).astype(np.float32)
    b_np = rng.random((16, 16)).astype(np.float32)
    c_np = rng.random((16, 16)).astype(np.float32)
    c_orig = c_np.copy()
    # Checkerboard mask
    mask_np = np.zeros((16, 16), dtype=np.float32)
    mask_np[::2, ::2] = 1.0
    mask_np[1::2, 1::2] = 1.0

    sdfg = pybe_ifelse_float_mask.to_sdfg(simplify=True)
    _pipeline_py(sdfg)
    csdfg = sdfg.compile()

    csdfg(
        A=cp.asarray(a_np), B=cp.asarray(b_np),
        Mask=cp.asarray(mask_np), C=(c_cp := cp.asarray(c_np))
    )
    expected = np.where(mask_np > 0, a_np + b_np, c_orig)
    np.testing.assert_allclose(cp.asnumpy(c_cp), expected, rtol=1e-5, atol=1e-6)


@pytest.mark.gpu
def test_ifelse_symbolic_size_python_backend():
    """Symbolic SZ: A > 0 → B−=1 else B+=1, runtime SZ=16."""
    rng = np.random.default_rng(3012)
    n = 16
    a_np = rng.standard_normal((n, n)).astype(np.float32)
    b_np = rng.random((n, n)).astype(np.float32)
    b_orig = b_np.copy()

    sdfg = pybe_ifelse_symbolic.to_sdfg(simplify=True)
    _pipeline_py(sdfg)
    csdfg = sdfg.compile()

    csdfg(_A=cp.asarray(a_np), _B=(b_cp := cp.asarray(b_np)), SZ=n)
    expected = np.where(a_np > 0, b_orig - 1.0, b_orig + 1.0)
    np.testing.assert_allclose(cp.asnumpy(b_cp), expected, rtol=1e-5, atol=1e-6)


# ---------------------------------------------------------------------------
# Section C: TileSymbolicMaskedOp — Python backend structural tests (no GPU)
# ---------------------------------------------------------------------------


class TestSymbolicMaskedPythonBackendStructure:
    """Strided @dace.program maps generate TileSymbolicMaskedOpLibraryNode.
    These tests verify the node type is produced and the Python backend
    code contains the expected coordinate-tile patterns (ct.arange, ct.where).

    No GPU required.
    """

    def test_stride2_produces_symbolic_masked_node(self):
        """Stride-2 map must produce at least one TileSymbolicMaskedOpLibraryNode."""
        sdfg = pybe_strided_i2_add.to_sdfg(simplify=True)
        _pipeline_py(sdfg, apply_map_collapse_and_tiling=True, tile_shape=(16, 16))
        sym_count = _count(sdfg, TileSymbolicMaskedOpLibraryNode)
        assert sym_count >= 1, (
            f"Expected TileSymbolicMaskedOpLibraryNode from strided map, got {sym_count}"
        )

    def test_stride2_symbolic_node_implementation_is_cutile_python(self):
        """All TileSymbolicMaskedOpLibraryNode instances must have cutile_python implementation."""
        sdfg = pybe_strided_i2_add.to_sdfg(simplify=True)
        _pipeline_py(sdfg, apply_map_collapse_and_tiling=True, tile_shape=(16, 16))
        sym_nodes = [n for n in _lib_nodes(sdfg) if isinstance(n, TileSymbolicMaskedOpLibraryNode)]
        assert sym_nodes, "No TileSymbolicMaskedOpLibraryNode found"
        assert all(n.implementation == "cutile_python" for n in sym_nodes)

    def test_stride2_codegen_has_ct_arange(self):
        """Strided map Python backend must emit ct.arange for coordinate tile."""
        sdfg = pybe_strided_i2_add.to_sdfg(simplify=True)
        _pipeline_py(sdfg, apply_map_collapse_and_tiling=True, tile_shape=(16, 16))
        code = _frame_code_of(sdfg)
        assert "ct.arange" in code, "Expected ct.arange for coordinate tile generation"

    def test_stride2_codegen_has_ct_where(self):
        """Strided map Python backend: masked elements must use ct.where."""
        sdfg = pybe_strided_i2_add.to_sdfg(simplify=True)
        _pipeline_py(sdfg, apply_map_collapse_and_tiling=True, tile_shape=(16, 16))
        code = _frame_code_of(sdfg)
        assert "ct.where" in code, "Expected ct.where for mask application"

    def test_j_stride2_produces_symbolic_masked_node(self):
        """Stride-2 in the j dimension also generates TileSymbolicMaskedOpLibraryNode."""
        sdfg = pybe_strided_j2_mul.to_sdfg(simplify=True)
        _pipeline_py(sdfg, apply_map_collapse_and_tiling=True, tile_shape=(16, 16))
        sym_count = _count(sdfg, TileSymbolicMaskedOpLibraryNode)
        assert sym_count >= 1

    def test_offset_stride_produces_symbolic_masked_node(self):
        """Non-zero start + stride also generates TileSymbolicMaskedOpLibraryNode."""
        sdfg = pybe_strided_offset_add.to_sdfg(simplify=True)
        _pipeline_py(sdfg, apply_map_collapse_and_tiling=True, tile_shape=(16, 16))
        sym_count = _count(sdfg, TileSymbolicMaskedOpLibraryNode)
        assert sym_count >= 1


# ---------------------------------------------------------------------------
# Section D: TileSymbolicMaskedOp — Python backend GPU runtime tests
# ---------------------------------------------------------------------------


@pytest.mark.gpu
def test_symbolic_masked_stride2_i_add_python_backend():
    """Stride-2 in i: only even rows get C = A + B; odd rows preserve initial C.

    Full path: @dace.program → Python backend → apply_cutile_pipeline
              → GPU compile → run → NumPy reference check.
    """
    rng = np.random.default_rng(4001)
    a_np = rng.random((32, 16)).astype(np.float32)
    b_np = rng.random((32, 16)).astype(np.float32)
    c_init = rng.random((32, 16)).astype(np.float32)
    c_np = c_init.copy()

    sdfg = pybe_strided_i2_add.to_sdfg(simplify=True)
    _pipeline_py(sdfg, apply_map_collapse_and_tiling=True, tile_shape=(16, 16))
    csdfg = sdfg.compile()
    assert csdfg is not None

    csdfg(A=cp.asarray(a_np), B=cp.asarray(b_np), C=(c_cp := cp.asarray(c_np)))
    result = cp.asnumpy(c_cp)

    # Even rows must equal A + B
    np.testing.assert_allclose(result[0::2, :], (a_np + b_np)[0::2, :], rtol=1e-5, atol=1e-6)
    # Odd rows must be unchanged
    np.testing.assert_allclose(result[1::2, :], c_init[1::2, :], rtol=1e-5, atol=1e-6)


@pytest.mark.gpu
def test_symbolic_masked_stride2_i_negate_python_backend():
    """Stride-2 negate: even rows get C = -A; odd rows preserve initial C."""
    rng = np.random.default_rng(4002)
    a_np = rng.standard_normal((32, 16)).astype(np.float32)
    c_init = rng.random((32, 16)).astype(np.float32)
    c_np = c_init.copy()

    sdfg = pybe_strided_i2_negate.to_sdfg(simplify=True)
    _pipeline_py(sdfg, apply_map_collapse_and_tiling=True, tile_shape=(16, 16))
    csdfg = sdfg.compile()
    assert csdfg is not None

    csdfg(A=cp.asarray(a_np), C=(c_cp := cp.asarray(c_np)))
    result = cp.asnumpy(c_cp)

    np.testing.assert_allclose(result[0::2, :], (-a_np)[0::2, :], rtol=1e-5, atol=1e-6)
    np.testing.assert_allclose(result[1::2, :], c_init[1::2, :], rtol=1e-5, atol=1e-6)


@pytest.mark.gpu
def test_symbolic_masked_stride2_j_mul_python_backend():
    """Stride-2 in j: only even columns get C = A * B; odd columns preserved."""
    rng = np.random.default_rng(4003)
    a_np = rng.random((16, 32)).astype(np.float32)
    b_np = rng.random((16, 32)).astype(np.float32)
    c_init = rng.random((16, 32)).astype(np.float32)
    c_np = c_init.copy()

    sdfg = pybe_strided_j2_mul.to_sdfg(simplify=True)
    _pipeline_py(sdfg, apply_map_collapse_and_tiling=True, tile_shape=(16, 16))
    csdfg = sdfg.compile()
    assert csdfg is not None

    csdfg(A=cp.asarray(a_np), B=cp.asarray(b_np), C=(c_cp := cp.asarray(c_np)))
    result = cp.asnumpy(c_cp)

    np.testing.assert_allclose(result[:, 0::2], (a_np * b_np)[:, 0::2], rtol=1e-5, atol=1e-6)
    np.testing.assert_allclose(result[:, 1::2], c_init[:, 1::2], rtol=1e-5, atol=1e-6)


@pytest.mark.gpu
def test_symbolic_masked_offset_stride_add_python_backend():
    """Non-zero start + stride-2: rows 2,4,6,...,14 updated; rows 0,1,3,5,...,15 preserved."""
    rng = np.random.default_rng(4004)
    a_np = rng.random((16, 16)).astype(np.float32)
    b_np = rng.random((16, 16)).astype(np.float32)
    c_init = rng.random((16, 16)).astype(np.float32)
    c_np = c_init.copy()

    sdfg = pybe_strided_offset_add.to_sdfg(simplify=True)
    _pipeline_py(sdfg, apply_map_collapse_and_tiling=True, tile_shape=(16, 16))
    csdfg = sdfg.compile()
    assert csdfg is not None

    csdfg(A=cp.asarray(a_np), B=cp.asarray(b_np), C=(c_cp := cp.asarray(c_np)))
    result = cp.asnumpy(c_cp)

    # Rows 2,4,6,...,14 (range 2:16:2) must equal A + B
    updated_rows = list(range(2, 16, 2))
    np.testing.assert_allclose(result[updated_rows, :], (a_np + b_np)[updated_rows, :],
                                rtol=1e-5, atol=1e-6)
    # Rows 0,1,3,5,...,15 must be unchanged
    unchanged_rows = [r for r in range(16) if r not in updated_rows]
    np.testing.assert_allclose(result[unchanged_rows, :], c_init[unchanged_rows, :],
                                rtol=1e-5, atol=1e-6)


def test_symbolic_masked_stride2_add_validates_sdfg():
    """SDFG with strided map and Python backend must pass validation before compile."""
    sdfg = pybe_strided_i2_add.to_sdfg(simplify=True)
    _pipeline_py(sdfg, apply_map_collapse_and_tiling=True, tile_shape=(16, 16))
    sdfg.expand_library_nodes()
    sdfg.validate()


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
